import socket

CLIENT_HOST = socket.gethostbyname("client")
CLIENT_PORT = 8000

SERVER_HOST = socket.gethostbyname("server")
SERVER_PORT = 8000

WAITING = 0
RECEIVED = 1

RETRANSMISSION_TIMEOUT = 1

WINDOW_SIZE = 60

DATA_PAYLOAD_SIZE = 3000

DATA_HEADER_SIZE = 36
DATA_TOTAL_SIZE = DATA_PAYLOAD_SIZE + DATA_HEADER_SIZE

ACK_SIZE = 20

NUMBER_OF_FILES = 20
